{
 "title": "Caps > Caps > Caps",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Carriers",
   "type": "table",
   "gridPos": { "h": 32, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n    sum(assets.quantity) as \"Count\",\n    IFNULL(el.location_name, IFNULL((select name from corptools_mapsystem where system_id = assets.location_id), concat(\"Unknown (\",assets.location_id,\")\"))) as \"Location\"\nfrom\n    corptools_characterasset assets\n    join corptools_characteraudit ac on assets.character_id = ac.id\n    join eveonline_evecharacter ec on ac.character_id = ec.id\n    join corptools_eveitemtype it on assets.type_id = it.type_id\n    join corptools_eveitemgroup ig on it.group_id = ig.group_id\n    left outer join corptools_evelocation el on assets.location_name_id = el.location_id\nwhere\n  it.group_id = 547 and ac.last_update_assets >= NOW() - INTERVAL 48 HOUR\ngroup by 2\norder by 1 desc"
    }
   ]
  },
  {
   "title": "Dreads",
   "type": "table",
   "gridPos": { "h": 32, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n    sum(assets.quantity) as \"Count\",\n    IFNULL(el.location_name, IFNULL((select name from corptools_mapsystem where system_id = assets.location_id), concat(\"Unknown (\",assets.location_id,\")\"))) as \"Location\"\nfrom\n    corptools_characterasset assets\n    join corptools_characteraudit ac on assets.character_id = ac.id\n    join eveonline_evecharacter ec on ac.character_id = ec.id\n    join corptools_eveitemtype it on assets.type_id = it.type_id\n    join corptools_eveitemgroup ig on it.group_id = ig.group_id\n    left outer join corptools_evelocation el on assets.location_name_id = el.location_id\nwhere\n  it.group_id = 485 and ac.last_update_assets >= NOW() - INTERVAL 48 HOUR\ngroup by 2\norder by 1 desc"
    }
   ]
  },
  {
   "title": "Super Carriers",
   "type": "table",
   "gridPos": { "h": 32, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n    sum(assets.quantity) as \"Count\",\n    IFNULL(el.location_name, IFNULL((select name from corptools_mapsystem where system_id = assets.location_id), concat(\"Unknown (\",assets.location_id,\")\"))) as \"Location\"\nfrom\n    corptools_characterasset assets\n    join corptools_characteraudit ac on assets.character_id = ac.id\n    join eveonline_evecharacter ec on ac.character_id = ec.id\n    join corptools_eveitemtype it on assets.type_id = it.type_id\n    join corptools_eveitemgroup ig on it.group_id = ig.group_id\n    left outer join corptools_evelocation el on assets.location_name_id = el.location_id\nwhere\n  it.group_id = 659 and ac.last_update_assets >= NOW() - INTERVAL 48 HOUR\ngroup by 2\norder by 1 desc"
    }
   ]
  },
  {
   "title": "Titans",
   "type": "table",
   "gridPos": { "h": 32, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n    sum(assets.quantity) as \"Count\",\n    IFNULL(el.location_name, IFNULL((select name from corptools_mapsystem where system_id = assets.location_id), concat(\"Unknown (\",assets.location_id,\")\"))) as \"Location\"\nfrom\n    corptools_characterasset assets\n    join corptools_characteraudit ac on assets.character_id = ac.id\n    join eveonline_evecharacter ec on ac.character_id = ec.id\n    join corptools_eveitemtype it on assets.type_id = it.type_id\n    join corptools_eveitemgroup ig on it.group_id = ig.group_id\n    left outer join corptools_evelocation el on assets.location_name_id = el.location_id\nwhere\n  it.group_id = 30 and ac.last_update_assets >= NOW() - INTERVAL 48 HOUR\ngroup by 2\norder by 1 desc"
    }
   ]
  }
 ]
}