{
 "title": "SRP",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Total SRP Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  srp_ship_name AS metric,\n  count(id) AS \"id\"\nFROM srp_srpuserrequest\nWHERE\n  $__timeFilter(post_time)\nORDER BY 2 desc\n"
    }
   ]
  },
  {
   "title": "Total SRP Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  srp_ship_name AS metric,\n  sum(srp_total_amount) AS \"id\"\nFROM srp_srpuserrequest\nWHERE\n  $__timeFilter(post_time)\nORDER BY 2 desc"
    }
   ]
  },
  {
   "title": "Average SRP Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  srp_ship_name AS metric,\n  avg(srp_total_amount) AS \"id\"\nFROM srp_srpuserrequest\nWHERE\n  $__timeFilter(post_time)\nORDER BY 2 desc"
    }
   ]
  },
  {
   "title": "Total SRP Requests",
   "type": "bargauge",
   "gridPos": { "h": 29, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  srp_ship_name AS metric,\n  count(id) AS \"id\"\nFROM srp_srpuserrequest\nWHERE\n  $__timeFilter(post_time)\nGROUP BY srp_ship_name\nORDER BY 2 desc\n"
    }
   ]
  },
  {
   "title": "Total SRP Cost",
   "type": "bargauge",
   "gridPos": { "h": 29, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  srp_ship_name AS metric,\n  sum(srp_total_amount) AS \"id\"\nFROM srp_srpuserrequest\nWHERE\n  $__timeFilter(post_time)\nGROUP BY srp_ship_name\nORDER BY 2 desc"
    }
   ]
  },
  {
   "title": "Average SRP Cost",
   "type": "bargauge",
   "gridPos": { "h": 29, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  srp_ship_name AS metric,\n  avg(srp_total_amount) AS \"id\"\nFROM srp_srpuserrequest\nWHERE\n  $__timeFilter(post_time)\nGROUP BY srp_ship_name\nORDER BY 2 desc"
    }
   ]
  }
 ]
}