global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - localhost:9090

  - job_name: "auth"
    static_configs:
    - targets: 
      - allianceauth:8099

  - job_name: 'traefik'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
    - targets: ['traefik:8080']